name: gotrue
description: A dart client library for the GoTrue API.
version: 0.0.1-dev.4
homepage: "https://supabase.io"
repository: "https://github.com/supabase/gotrue-dart"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2

dev_dependencies:
  test: ^1.15.4
  lint: ^1.3.0
